### ISSUE TITLE
 Introduce CircleCI support and Codecov

### ISSUE THREAD

**Issue by jrgriffiniii** [samvera-labs/browse-everything-redux-react#18]
Codecov should support code coverage analysis for JavaScript and TypeScript: https://docs.codecov.io/docs/supported-languages

This should be in place before #1 is merged (just to provide some sense for what needs to be addressed).

**Comment by jrgriffiniii** [comment]
Perhaps we should be testing against different Node releases?

**Comment by christinach** [comment]
closed by #38
